import random
import re


class FerryRateLedgerEnv:
    """Hidden triangle-wave integer sequence; solver infers the two-stage
    rise/fall rule from budgeted queries and extrapolates to sealed indices."""

    N = 30
    RESERVED = (27, 28, 29)
    MAX_STEPS = 10

    def __init__(self):
        self.rng = None
        self.L = None
        self.W = None
        self.s = None
        self.d0 = None
        self.steps = 0
        self.done = False

    def reset(self, seed=None):
        self.rng = random.Random(seed)
        self.L = self.rng.randint(0, 5)
        self.W = self.rng.randint(8, 14)
        self.s = self.rng.randint(1, 3)
        self.d0 = self.rng.randint(0, self.W)
        self.steps = 0
        self.done = False
        obs = (
            "You face a hidden integer ledger a(0..29) generated by a two-stage "
            "rule: values rise for a while, then fall, then would rise again if "
            "the ledger continued further. Indices 27, 28, 29 are SEALED and "
            "cannot be queried directly -- you must deduce their values from "
            "the pattern you observe elsewhere.\n"
            "Actions:\n"
            "  QUERY <n>  -- reveal a(n) for an unsealed index n in [0,26]\n"
            "  ANSWER <v27> <v28> <v29> -- submit your final predicted values, "
            "in order, for the three sealed indices. This ends the episode.\n"
            f"You have {self.MAX_STEPS} total actions. Reward is granted per "
            "correct sealed value (partial credit for getting some right)."
        )
        return obs, {}

    def _value_at(self, n):
        period = 2 * self.W
        raw = (self.d0 + self.s * n) % period
        if raw <= self.W:
            return self.L + raw
        return self.L + (period - raw)

    def _finish_if_out_of_steps(self, obs):
        if self.steps >= self.MAX_STEPS:
            self.done = True
            return obs, 0.0, False, True, {}
        return obs, 0.0, False, False, {}

    def step(self, action):
        if self.done:
            return "Episode already over.", 0.0, True, False, {}

        self.steps += 1
        action = (action or "").strip()

        m = re.fullmatch(r"QUERY\s+(-?\d+)", action, re.IGNORECASE)
        if m:
            n = int(m.group(1))
            if n in self.RESERVED:
                obs = f"Index {n} is sealed and cannot be queried."
                return self._finish_if_out_of_steps(obs)
            if not (0 <= n <= 26):
                obs = f"Index {n} is out of range [0,26]."
                return self._finish_if_out_of_steps(obs)
            val = self._value_at(n)
            obs = f"a({n}) = {val}"
            return self._finish_if_out_of_steps(obs)

        m = re.fullmatch(
            r"ANSWER\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)", action, re.IGNORECASE
        )
        if m:
            guesses = [int(m.group(i)) for i in (1, 2, 3)]
            truths = [self._value_at(n) for n in self.RESERVED]
            correct = sum(1 for g, t in zip(guesses, truths) if g == t)
            reward = correct / 3.0
            self.done = True
            obs = (
                f"Final answer recorded: {correct}/3 sealed values correct. "
                f"Truth was a(27)={truths[0]}, a(28)={truths[1]}, a(29)={truths[2]}."
            )
            return obs, reward, True, False, {}

        obs = (
            "Malformed action. Use 'QUERY <n>' with 0<=n<=26, or "
            "'ANSWER <v27> <v28> <v29>' with three integers."
        )
        return self._finish_if_out_of_steps(obs)
