import random
import re


class SplitLedgerEnv:
    """
    A ledger of integer readings at positions 0..19 is generated by two
    hidden arithmetic progressions, one governing even positions and one
    governing odd positions. The solver must REVEAL positions to gather
    evidence, then SOLVE with the four hidden parameters.
    """

    MAX_STEPS = 10
    MAX_POS = 19

    def __init__(self):
        self.rng = None
        self.a1 = self.d1 = self.a2 = self.d2 = None
        self.step_count = 0
        self.correct_params = set()
        self.terminated = False
        self.truncated = False

    def reset(self, seed=None):
        self.rng = random.Random(seed)
        while True:
            self.a1 = self.rng.randint(1, 12)
            self.a2 = self.rng.randint(1, 12)
            self.d1 = self._nonzero_step()
            self.d2 = self._nonzero_step()
            if not (self.a1 == self.a2 and self.d1 == self.d2):
                break

        self.step_count = 0
        self.correct_params = set()
        self.terminated = False
        self.truncated = False

        obs = (
            "SPLIT LEDGER. An old ledger records integer readings at "
            f"positions 0 through {self.MAX_POS}. The readings are produced "
            "by a hidden rule with two internal stages: something first "
            "sorts each position into one of two tracks, and each track "
            "then produces its own arithmetic run. Your job is to recover "
            "the starting value and step size of BOTH tracks.\n\n"
            "Actions (exactly one per turn):\n"
            "  REVEAL <n>            -- read the ledger value at position n "
            f"(0<=n<={self.MAX_POS})\n"
            "  SOLVE <a1> <d1> <a2> <d2>  -- submit start/step for track 1 "
            "and start/step for track 2 (you decide which track you call "
            "'1' and which you call '2')\n\n"
            f"You have {self.MAX_STEPS} actions total. Each of the 4 "
            "submitted numbers is checked independently and stays credited "
            "once correct, even across repeated SOLVE attempts."
        )
        return obs, {}

    def _nonzero_step(self):
        mag = self.rng.randint(1, 6)
        sign = self.rng.choice([-1, 1])
        return mag * sign

    def _true_value(self, n):
        k = n // 2
        if n % 2 == 0:
            return self.a1 + k * self.d1
        return self.a2 + k * self.d2

    def step(self, action):
        if self.terminated or self.truncated:
            return "Episode already finished.", 0.0, self.terminated, self.truncated, {}

        self.step_count += 1
        action = (action or "").strip()

        reveal_match = re.match(r"^REVEAL\s+(-?\d+)\s*$", action, re.IGNORECASE)
        solve_match = re.match(
            r"^SOLVE\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)\s*$",
            action,
            re.IGNORECASE,
        )

        reward = 0.0
        obs = ""

        if reveal_match:
            n = int(reveal_match.group(1))
            if n < 0 or n > self.MAX_POS:
                obs = (
                    f"Invalid position {n}. Positions must satisfy "
                    f"0<=n<={self.MAX_POS}. No reading taken."
                )
            else:
                val = self._true_value(n)
                obs = f"Ledger[{n}] = {val}"
        elif solve_match:
            guesses = [int(g) for g in solve_match.groups()]
            truth = [self.a1, self.d1, self.a2, self.d2]
            names = ["a1", "d1", "a2", "d2"]
            lines = []
            newly = 0
            for idx, (g, t, name) in enumerate(zip(guesses, truth, names)):
                if g == t:
                    if idx not in self.correct_params:
                        self.correct_params.add(idx)
                        newly += 1
                    lines.append(f"{name}: correct")
                elif g > t:
                    lines.append(f"{name}: too high")
                else:
                    lines.append(f"{name}: too low")
            reward = 0.25 * newly
            obs = "SOLVE result -> " + ", ".join(lines)
            if len(self.correct_params) == 4:
                obs += "\nAll four parameters confirmed. Ledger fully decoded."
                self.terminated = True
        else:
            obs = (
                "Unrecognized action. Use 'REVEAL <n>' or "
                "'SOLVE <a1> <d1> <a2> <d2>' with integer arguments."
            )

        if not self.terminated and self.step_count >= self.MAX_STEPS:
            self.truncated = True

        info = {"correct_params": len(self.correct_params)}
        return obs, reward, self.terminated, self.truncated, info
