"""Regenerate the live-status block in README.md from runs/.

Reads the committed run logs and rewrites everything between the
STATUS:BEGIN / STATUS:END markers, so the README always reflects the data
actually on disk rather than a hand-written snapshot.

    python3 tools/render_status.py          # rewrite README.md in place
    python3 tools/render_status.py --print   # print the block, change nothing
"""

from __future__ import annotations

import json
import statistics as st
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "runs"
CONDITIONS = ("c0", "c1", "c2")
LABEL = {"c0": "C0 static", "c1": "C1 memory", "c2": "C2 memory+evolution"}
ROUNDS_PLANNED = 6
ENVS_PER_ROUND = 6


def _jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    out = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if line:
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return out


def _probe(name: str) -> dict | None:
    for fn in ("probe_report.json", "probe_report.reconstructed.json"):
        p = RUNS / name / fn
        if p.exists():
            d = json.loads(p.read_text())
            d["_source"] = fn
            return d
    return None


def _fmt(x, nd=4):
    return "—" if x is None else f"{x:.{nd}f}"


def render() -> str:
    L: list[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    try:
        sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                             capture_output=True, text=True).stdout.strip()
    except Exception:
        sha = "?"

    rounds = {c: _jsonl(RUNS / c / "rounds.jsonl") for c in CONDITIONS}
    envs = {c: _jsonl(RUNS / c / "envs.jsonl") for c in CONDITIONS}
    done = sum(len(rounds[c]) for c in CONDITIONS)
    total = ROUNDS_PLANNED * len(CONDITIONS)
    env_done = sum(len(envs[c]) for c in CONDITIONS)
    env_total = ROUNDS_PLANNED * ENVS_PER_ROUND * len(CONDITIONS)

    L += [f"_Auto-generated by `tools/render_status.py` at {now} from commit `{sha}`._", ""]
    L += [f"**S3 main grid: {done}/{total} rounds complete "
          f"({env_done}/{env_total} environments).**", ""]

    # ---- gates ----
    L += ["### Pre-registered gates (R1–R3)", ""]
    L += ["| probe | R1 interface | R2 spread | R3 headroom | verdict |",
          "|---|---|---|---|---|"]
    for name, note in (("probe_s0", "original, pre-A2"), ("probe_s0_a2", "fresh, under A2 — **gates the grid**")):
        p = _probe(name)
        if not p:
            continue
        r1, r2, r3 = p["R1_interface"], p["R2_spread"], p["R3_headroom"]
        ok = lambda b: "PASS" if b else "FAIL"  # noqa: E731
        verdict = "PASS" if all(x["pass"] for x in (r1, r2, r3)) else "FAIL"
        L.append(f"| `{name}` ({note}) | {ok(r1['pass'])} {r1['valid']} | "
                 f"{ok(r2['pass'])} {r2['spread']} | {ok(r3['pass'])} "
                 f"fitness {r3['S0_fitness']} | **{verdict}** |")
    L += ["", "R1 needs ≥5/10 valid · R2 needs spread ≥0.15 · R3 fails only if S0 already saturates.", ""]

    # ---- trajectory ----
    L += ["### Round fitness trajectory", "",
          "| round | C0 static | C1 memory | C2 memory+evolution | C2 strategy |",
          "|---|---|---|---|---|"]
    for r in range(ROUNDS_PLANNED):
        cells = []
        for c in CONDITIONS:
            cells.append(_fmt(rounds[c][r]["fitness"]) if r < len(rounds[c]) else "·")
        strat = rounds["c2"][r]["strategy_id"] if r < len(rounds["c2"]) else "·"
        L.append(f"| r{r} | {cells[0]} | {cells[1]} | {cells[2]} | {strat} |")
    summ = []
    for c in CONDITIONS:
        f = [x["fitness"] for x in rounds[c]]
        summ.append(f"{st.mean(f):.4f}" if f else "—")
    L.append(f"| **mean** | **{summ[0]}** | **{summ[1]}** | **{summ[2]}** | |")
    sds = []
    for c in CONDITIONS:
        f = [x["fitness"] for x in rounds[c]]
        sds.append(f"{st.stdev(f):.4f}" if len(f) > 1 else "—")
    L.append(f"| sd | {sds[0]} | {sds[1]} | {sds[2]} | |")
    L += ["", "Fitness = mean floored hint-based regret over valid environments. "
          "**No conclusion is drawn from these numbers** — see the caveats below.", ""]

    # ---- headline descriptive ----
    raw = [e["raw_regret"] for c in CONDITIONS for e in envs[c]
           if e.get("raw_regret") is not None]
    if raw:
        helped = sum(1 for x in raw if x > 0)
        harmed = sum(1 for x in raw if x < 0)
        neutral = sum(1 for x in raw if x == 0)
        L += ["### Does the hint actually help? (raw vs floored regret)", "",
              "Selective fitness floors regret at zero, so every case where a hint made the "
              "solver *worse* is recorded as `0.0000`. Amendment A2 logs the raw gap so those "
              "cases stay visible:", "",
              "| environments | hint helped | hint harmed | no effect |",
              "|---|---|---|---|",
              f"| {len(raw)} | {helped} | **{harmed}** | {neutral} |", "",
              f"mean raw regret **{st.mean(raw):+.4f}** · median {st.median(raw):+.4f} · "
              f"range {min(raw):+.4f} to {max(raw):+.4f}", "",
              f"All {harmed} harmed environments contribute exactly `0.0000` to fitness — "
              "indistinguishable from a hint that did nothing.", ""]

    # ---- census ----
    cens = Counter()
    per = {}
    for c in CONDITIONS:
        pc = Counter()
        for e in envs[c]:
            stage = e.get("stage")
            iss = (e.get("gate_issues") or [""])[0]
            if stage == "evaluated":
                k = "evaluated"
            elif stage == "design":
                k = "designer timeout"
            elif "hint exceeds" in iss:
                k = "V2 hint too long"
            else:
                k = "other gate"
            pc[k] += 1
            cens[k] += 1
        per[c] = pc
    L += ["### Environment outcomes", "",
          "| condition | evaluated | V2 hint too long | designer timeout | other gate | yield |",
          "|---|---|---|---|---|---|"]
    for c in CONDITIONS:
        n = sum(per[c].values())
        y = f"{100 * per[c]['evaluated'] / n:.0f}%" if n else "—"
        L.append(f"| {LABEL[c]} | {per[c]['evaluated']} | {per[c]['V2 hint too long']} | "
                 f"{per[c]['designer timeout']} | {per[c]['other gate']} | {y} |")
    L += ["", ""]

    return "\n".join(L)


def main(argv: list[str]) -> int:
    block = render()
    if "--print" in argv:
        print(block)
        return 0
    readme = ROOT / "README.md"
    text = readme.read_text()
    b, e = "<!-- STATUS:BEGIN -->", "<!-- STATUS:END -->"
    if b not in text or e not in text:
        print("markers missing from README.md", file=sys.stderr)
        return 1
    pre, rest = text.split(b, 1)
    _, post = rest.split(e, 1)
    readme.write_text(f"{pre}{b}\n{block}{e}{post}")
    print("README.md status block updated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
