import random


def _bit(rule, idx):
    return (rule >> idx) & 1


def _rule_table(rule):
    return [_bit(rule, idx) for idx in range(8)]


def _depends_on_all_three(table):
    for weight in (4, 2, 1):
        changed = False
        for idx in range(8):
            j = idx ^ weight
            if table[idx] != table[j]:
                changed = True
                break
        if not changed:
            return False
    return True


_VALID_RULES = [r for r in range(1, 255) if _depends_on_all_three(_rule_table(r))]


class CellularAutomatonPredictEnv:
    """Solver must infer a hidden 1D elementary-CA rule from revealed
    example transitions, then predict the next state of a held-out row."""

    N = 8
    MAX_STEPS = 10

    def reset(self, seed=None):
        self.rng = random.Random(seed)
        self.rule = self.rng.choice(_VALID_RULES)
        self.table = _rule_table(self.rule)
        self.target_row = [self.rng.randint(0, 1) for _ in range(self.N)]
        self.target_next, _ = self._apply_rule(self.target_row)
        self.steps = 0
        self.example_count = 0
        self.seen_neighborhoods = set()
        self.milestone_awarded = False
        self.done = False
        obs = self._render_intro()
        return obs, {}

    def _apply_rule(self, row):
        n = self.N
        next_row = []
        idxs = []
        for i in range(n):
            left = row[(i - 1) % n]
            center = row[i]
            right = row[(i + 1) % n]
            idx = left * 4 + center * 2 + right
            next_row.append(self.table[idx])
            idxs.append(idx)
        return next_row, idxs

    def _bits_to_str(self, bits):
        return "".join(str(b) for b in bits)

    def _render_intro(self):
        target = self._bits_to_str(self.target_row)
        return (
            "GOAL: A hidden 1D cellular automaton updates a circular row of "
            f"{self.N} cells (0/1). Each cell's next value depends only on the "
            "3-cell neighborhood (left, center, right) around it, via a fixed "
            "but hidden lookup table with exactly 8 possible neighborhood "
            "patterns. Your job: predict the next-state row for the TARGET "
            "row below after ONE application of the hidden rule.\n"
            f"TARGET ROW: {target}\n"
            "ACTIONS (exactly one per turn):\n"
            "  REVEAL              - see one new example transition (a fresh "
            "random row and its next-state row, generated by the SAME hidden "
            "rule) to gather evidence.\n"
            f"  PREDICT <{self.N}-bit string>  - submit your final answer for "
            "the target row's next state, e.g. PREDICT 01101001. Ends the "
            "episode.\n"
            f"You have at most {self.MAX_STEPS} total actions."
        )

    def step(self, action):
        if self.done:
            return "Episode already finished.", 0.0, True, False, {}

        self.steps += 1
        text = (action or "").strip()
        upper = text.upper()

        if upper == "REVEAL":
            obs, reward = self._do_reveal()
            terminated = False
        elif upper.startswith("PREDICT"):
            obs, reward, terminated = self._do_predict(text)
        else:
            obs = (
                "Malformed action. Use exactly 'REVEAL' or "
                f"'PREDICT <{self.N}-bit string>'."
            )
            reward = 0.0
            terminated = False

        truncated = False
        if not terminated and self.steps >= self.MAX_STEPS:
            truncated = True
            self.done = True
            obs = obs + f" Step limit ({self.MAX_STEPS}) reached; episode over."
        if terminated:
            self.done = True

        info = {"steps_used": self.steps}
        return obs, reward, terminated, truncated, info

    def _do_reveal(self):
        row = [self.rng.randint(0, 1) for _ in range(self.N)]
        next_row, idxs = self._apply_rule(row)
        self.example_count += 1
        newly_seen = set(idxs) - self.seen_neighborhoods
        self.seen_neighborhoods |= set(idxs)
        reward = 0.0
        if not self.milestone_awarded and len(self.seen_neighborhoods) == 8:
            self.milestone_awarded = True
            reward = 0.3
        obs = (
            f"Example {self.example_count}: row={self._bits_to_str(row)} -> "
            f"next={self._bits_to_str(next_row)} "
            f"(distinct neighborhood patterns observed so far: "
            f"{len(self.seen_neighborhoods)}/8) "
            f"[steps used: {self.steps}/{self.MAX_STEPS}]"
        )
        if reward > 0:
            obs += " All neighborhood patterns now witnessed at least once."
        return obs, reward

    def _do_predict(self, text):
        parts = text.split(None, 1)
        guess_str = parts[1].strip() if len(parts) > 1 else ""
        valid = len(guess_str) == self.N and all(c in "01" for c in guess_str)
        if not valid:
            obs = (
                f"Malformed PREDICT: expected exactly {self.N} characters of "
                "'0'/'1'. Try again."
            )
            return obs, 0.0, False

        guess = [int(c) for c in guess_str]
        correct = sum(1 for g, t in zip(guess, self.target_next) if g == t)
        reward = (correct / self.N) * 0.7
        target_str = self._bits_to_str(self.target_next)
        obs = (
            f"PREDICT {guess_str} -> correct next-state was {target_str}; "
            f"matched {correct}/{self.N} bits. Episode over."
        )
        return obs, reward, True
